# Generated by Django 5.0.4 on 2024-04-24 09:47

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.URLField(blank=True)),
                ('title', models.CharField(blank=True)),
                ('creator', models.CharField(blank=True)),
                ('date', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, size=None)),
                ('coverage', models.CharField(blank=True, choices=[('WORKPLACE', 'workplace'), ('SECTION', 'section'), ('DIVISION', 'division'), ('DISTRICT', 'district'), ('NATIONAL_BRANCH', 'national branch'), ('NATIONAL_FEDERATION', 'national federation'), ('INTERNATIONAL_BRANCH', 'international branch'), ('INTERNATIONAL_FEDERATION', 'international federation'), ('OTHER', 'other')], default='OTHER')),
                ('language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None)),
                ('spatial', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None)),
                ('type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ANNUAL_REPORT', 'annual report'), ('FINANCIAL_STATEMENT', 'financial statement')]), blank=True, size=None)),
                ('license', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None)),
                ('isVersionOf', models.URLField(blank=True)),
                ('isFormatOf', models.CharField(blank=True, choices=[('PRINTED', 'printed'), ('HANDWRITTEN', 'handwritten'), ('TYPEWRITTEN', 'typewritten'), ('DIGITAL', 'digital')])),
                ('relation', models.URLField(blank=True)),
                ('created', models.DateField(blank=True)),
                ('available', models.DateField(blank=True)),
                ('accessRights', models.CharField(blank=True, choices=[('RESTRICTED', 'restricted'), ('NOT_RESTRICTED', 'not restricted')], default='NOT_RESTRICTED')),
                ('source', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('ERROR', 'Error'), ('AWAITING_HUMAN_INPUT', 'Awaiting Human Input'), ('AWAITING_HUMAN_VALIDATION', 'Awaiting Human Validation')], default='PENDING')),
            ],
        ),
        migrations.CreateModel(
            name='UrlSettings',
            fields=[
                ('name', models.CharField(choices=[('IIIF', 'IIIF Base URL'), ('ATOM', 'AtoM Base URL')], primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='metadata.report')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('ERROR', 'Error'), ('AWAITING_HUMAN_INPUT', 'Awaiting Human Input'), ('AWAITING_HUMAN_VALIDATION', 'Awaiting Human Validation')], default='PENDING')),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='metadata.transfer')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('transcriptionFile', models.FileField(upload_to='')),
                ('identifier', models.URLField(blank=True)),
                ('transcription', models.TextField(blank=True)),
                ('normalisedTranscription', models.TextField(blank=True)),
                ('persons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None)),
                ('organisations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None)),
                ('locations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None)),
                ('times', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None)),
                ('works', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None)),
                ('events', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None)),
                ('ner_objects', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None)),
                ('measures', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.report')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.transfer'),
        ),
        migrations.CreateModel(
            name='ProcessingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processingStepType', models.CharField(choices=[('FILENAME', 'Filename-based extraction'), ('FILEMAKER_LOOKUP', 'Lookup in Filemaker export'), ('GENERATE', 'Generate/Calculate'), ('IMAGE', 'Image-based extraction'), ('NER', 'Named Entity Recognition'), ('MINT_ARKS', 'Mint ARKs')])),
                ('order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('ERROR', 'Error'), ('AWAITING_HUMAN_INPUT', 'Awaiting Human Input'), ('AWAITING_HUMAN_VALIDATION', 'Awaiting Human Validation')], default='PENDING')),
                ('log', models.TextField(blank=True)),
                ('humanValidation', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], default='AUTOMATIC')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processingSteps', to='metadata.job')),
            ],
        ),
    ]
