# Generated by Django 5.0.4 on 2024-04-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='unionId',
            field=models.CharField(blank=True),
        ),
    ]
