# Generated by Django 5.0.4 on 2024-04-26 13:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_report_unionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='events',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='page',
            name='identifier',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='page',
            name='ner_objects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='page',
            name='normalisedTranscription',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='organisations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='page',
            name='persons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='page',
            name='times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='page',
            name='transcription',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='transcriptionFile',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='works',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='available',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='creator',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='identifier',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='isFormatOf',
            field=models.CharField(blank=True, choices=[('PRINTED', 'printed'), ('HANDWRITTEN', 'handwritten'), ('TYPEWRITTEN', 'typewritten'), ('DIGITAL', 'digital')], null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='isVersionOf',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='license',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='relation',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='source',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='spatial',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ANNUAL_REPORT', 'annual report'), ('FINANCIAL_STATEMENT', 'financial statement')]), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='unionId',
            field=models.CharField(blank=True, default=''),
        ),
    ]
