# Generated by Django 5.0.4 on 2024-05-02 10:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_alter_page_events_alter_page_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='relation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
    ]
