# Generated by Django 5.0.4 on 2024-05-02 13:26

import django.contrib.postgres.fields
import metadata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_alter_report_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='spatial',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=metadata.models.spatialDefault, null=True, size=None),
        ),
    ]
