# Generated by Django 5.0.4 on 2024-05-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_alter_report_spatial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultNumberSettings',
            fields=[
                ('name', models.CharField(choices=[('AVAILABLE_YEAR_OFFSET', 'Number of years, calculated from date of publication, until the material becomes available')], primary_key=True, serialize=False)),
                ('value', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'default Number Settings',
            },
        ),
        migrations.AlterField(
            model_name='defaultvaluesettings',
            name='name',
            field=models.CharField(choices=[('DC_LANGUAGE', 'dcterms:language'), ('DC_LICENSE', 'dcterms:license'), ('DC_SOURCE', 'dcterms:source'), ('DC_ACCESS_RIGHTS', 'dcterms:accessRights')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='defaultvaluesettings',
            name='value',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='urlsettings',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
