# Generated by Django 5.0.4 on 2024-05-08 09:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_defaultnumbersettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='isFormatOf',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PRINTED', 'printed'), ('HANDWRITTEN', 'handwritten'), ('TYPEWRITTEN', 'typewritten'), ('DIGITAL', 'digital')]), blank=True, null=True, size=None),
        ),
    ]
