# Generated by Django 5.0.4 on 2024-05-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_alter_report_isformatof'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilemakerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archiveId', models.CharField()),
                ('organisationName', models.CharField()),
                ('county', models.CharField(blank=True, default='')),
                ('municipality', models.CharField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='')),
                ('parish', models.CharField(blank=True, default='')),
            ],
        ),
    ]
