# Generated by Django 5.0.4 on 2024-05-14 15:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_filemakerentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='isFormatOf',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PRINTED', 'printed'), ('HANDWRITTEN', 'handwritten'), ('TYPEWRITTEN', 'typewritten'), ('DIGITAL', 'digital')]), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ANNUAL_REPORT', 'annual report'), ('FINANCIAL_STATEMENT', 'financial statement')]), blank=True, default=list, null=True, size=None),
        ),
    ]
