# Generated by Django 5.0.4 on 2024-06-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_alter_report_isformatof_alter_report_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UrlSettings',
        ),
        migrations.AddField(
            model_name='report',
            name='noid',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='defaultvaluesettings',
            name='name',
            field=models.CharField(choices=[('DC_LANGUAGE', 'dcterms:language'), ('DC_LICENSE', 'dcterms:license'), ('DC_SOURCE', 'dcterms:source'), ('DC_ACCESS_RIGHTS', 'dcterms:accessRights'), ('ARK_SHOULDER', 'ARK Shoulder')], primary_key=True, serialize=False),
        ),
    ]
