# Generated by Django 5.0.4 on 2024-06-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_filemakerentry_nadlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='iiifId',
            field=models.CharField(blank=True, default=''),
        ),
    ]
