# Generated by Django 5.0.4 on 2024-06-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_page_iiifid'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='originalFileName',
            field=models.CharField(null=True),
        ),
    ]
