# Generated by Django 5.0.4 on 2024-06-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0013_page_originalfilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingstep',
            name='processingStepType',
            field=models.CharField(choices=[('FILENAME', 'Filename-based extraction'), ('FILEMAKER_LOOKUP', 'Lookup in Filemaker export'), ('GENERATE', 'Generate/Calculate'), ('IMAGE', 'Image-based extraction'), ('NER', 'Named Entity Recognition'), ('MINT_ARKS', 'Mint ARKs'), ('PipelineStepName.FAC_MANUAL', 'Manual')]),
        ),
    ]
