# Generated by Django 5.1.1 on 2024-10-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0020_externalrecord_coverage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalrecord',
            old_name='catalogueLink',
            new_name='relationLink',
        ),
        migrations.AddField(
            model_name='externalrecord',
            name='isVersionOfLink',
            field=models.URLField(blank=True, default=''),
        ),
    ]
