# Generated by Django 5.1.1 on 2024-11-06 12:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0021_rename_cataloguelink_externalrecord_relationlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingstep',
            name='processingStepType',
            field=models.CharField(choices=[('FILENAME', 'Filename-based extraction'), ('FILEMAKER_LOOKUP', 'Lookup in Filemaker export'), ('GENERATE', 'Generate/Calculate'), ('FAC_MANUAL', 'Manual'), ('IMAGE', 'Image-based extraction'), ('NER', 'Named Entity Recognition'), ('MINT_ARKS', 'Mint ARKs'), ('ARAB_GENERATE', 'Generate/Calculate'), ('ARAB_MANUAL', 'Manual'), ('ARAB_MINT_HANDLE', 'Mint Handle IDs'), ('ARAB_TRANSLATE_TO_SWEDISH', 'Translate to Swedish'), ('FAC_TRANSLATE_TO_SWEDISH', 'Translate to Swedish')]),
        ),
        migrations.CreateModel(
            name='ReportTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='')),
                ('coverage', models.CharField(blank=True, default='')),
                ('isFormatOf', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None)),
                ('type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None)),
                ('accessRights', models.CharField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.report')),
            ],
        ),
    ]
