# Generated by Django 5.1.1 on 2024-11-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0023_alter_defaultnumbersettings_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractiontransfer',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
