# Generated by Django 5.1.1 on 2024-12-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0025_job_lastupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='bibCitation',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='page',
            name='noid',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='page',
            name='source',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='defaultvaluesettings',
            name='name',
            field=models.CharField(choices=[('DC_LANGUAGE', 'dcterms:language'), ('DC_LICENSE', 'dcterms:license'), ('DC_SOURCE', 'dcterms:source'), ('DC_ACCESS_RIGHTS', 'dcterms:accessRights'), ('ARK_SHOULDER', 'ARK Shoulder (deprecated)'), ('REPORT_ARK_SHOULDER', 'Report-level ARK Shoulder'), ('PAGE_ARK_SHOULDER', 'Page-level ARK Shoulder')], primary_key=True, serialize=False),
        ),
    ]
