# Generated by Django 5.1.1 on 2024-12-19 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0026_page_bibcitation_page_noid_page_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacSpecificData',
            fields=[
                ('report', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='metadata.report')),
                ('seriesVolumeName', models.CharField(blank=True, default='')),
                ('seriesVolumeSignum', models.CharField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
