# Generated by Django 5.1.4 on 2025-02-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0027_facspecificdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='references',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='referencesNoid',
            field=models.CharField(blank=True, default=''),
        ),
    ]
