# Generated by Django 5.1.4 on 2025-02-05 15:15

import uuid
from django.db import migrations, models


def migrateIds(apps, schema_editor):
    MyModel = apps.get_model("metadata", "ExternalRecord")
    for row in MyModel.objects.all():
        row.recordId = row.archiveId
        row.save(update_fields=["recordId"])

class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0028_report_references_report_referencesnoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalrecord',
            name='endYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalrecord',
            name='recordId',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='externalrecord',
            name='startYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalrecord',
            name='archiveId',
            field=models.CharField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.RunPython(migrateIds, reverse_code=migrations.RunPython.noop),
    ]
