# Generated by Django 5.1.4 on 2025-02-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0030_rename_recordid_externalrecord_arabrecordid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalrecord',
            old_name='endYear',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='externalrecord',
            old_name='startYear',
            new_name='startDate',
        ),
    ]
