# Generated by Django 5.1.4 on 2025-02-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0031_rename_endyear_externalrecord_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractiontransfer',
            name='handler',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractiontransfer',
            name='pipeline',
            field=models.CharField(choices=[('FAC', 'Fac'), ('ARAB_LM', 'Arab Lm'), ('ARAB_OTHER', 'Arab Other')], null=True),
        ),
    ]
