# Generated by Django 5.1.4 on 2025-02-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0032_extractiontransfer_handler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='format',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='medium',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='publisher',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='type_other',
            field=models.CharField(blank=True, default=''),
        ),
    ]
