# Generated by Django 5.1.4 on 2025-02-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('standardTerm', models.CharField()),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.vocabulary')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vocabulary', 'standardTerm'), name='vocabulary-unique-standardTerm')],
            },
        ),
    ]
