# Generated by Django 5.1.4 on 2025-02-21 12:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('abbreviation', models.CharField(max_length=6)),
                ('description', models.TextField(blank=True)),
                ('recordIdColumnName', models.CharField()),
                ('externalRecordColumnNames', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=list, size=None)),
            ],
        ),
    ]
