# Generated by Django 5.1.4 on 2025-02-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='recordIdColumnName',
            field=models.CharField(blank=True),
        ),
    ]
