# Generated by Django 5.1.4 on 2025-02-21 14:58

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0003_alter_project_recordidcolumnname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicValueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valueTypes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PLAINTEXT', 'Plaintext'), ('URL', 'Url'), ('DATE', 'Date'), ('PLAIN HANDLE', 'Plain Handle'), ('LOCATION HANDLE', 'Location Handle')]), default=list, size=None)),
                ('multiple', models.BooleanField()),
                ('range', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceValueType',
            fields=[
                ('basicvaluetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v2.basicvaluetype')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
            ],
            bases=('v2.basicvaluetype',),
        ),
        migrations.CreateModel(
            name='ProjectMetadataTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory', models.BooleanField()),
                ('level', models.CharField(choices=[('ITEM', 'Item'), ('PAGE', 'Page')])),
                ('metadataTerm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.metadataterm')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.project')),
                ('valueType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.basicvaluetype')),
            ],
        ),
    ]
