# Generated by Django 5.1.4 on 2025-02-24 16:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0004_basicvaluetype_choicevaluetype_projectmetadataterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='prefix',
            field=models.CharField(default='prefix'),
        ),
        migrations.AlterField(
            model_name='choicevaluetype',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), default=list, size=None),
        ),
    ]
