# Generated by Django 5.1.4 on 2025-02-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0005_vocabulary_prefix_alter_choicevaluetype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='prefixSeparator',
            field=models.CharField(default='.'),
        ),
    ]
