# Generated by Django 5.1.4 on 2025-02-24 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0006_project_prefixseparator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalRecordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordId', models.CharField()),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.project')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalRecordField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField()),
                ('value', models.CharField(blank=True)),
                ('externalRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.externalrecordentry')),
            ],
        ),
    ]
