# Generated by Django 5.1.4 on 2025-02-25 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0007_externalrecordentry_externalrecordfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingStepConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('key', models.CharField()),
                ('description', models.CharField(blank=True, default='')),
                ('options', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.project')),
            ],
        ),
    ]
