# Generated by Django 5.1.4 on 2025-02-25 08:01

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0008_processingstepconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.project')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='v2.process')),
                ('recordId', models.CharField()),
                ('documentTypeIdentifier', models.CharField()),
                ('date', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalFilename', models.CharField()),
                ('file', models.FileField(upload_to='')),
                ('fileType', models.CharField(choices=[('IMAGE', 'Image'), ('PDF', 'Pdf'), ('XML_ALTO', 'Xml Alto'), ('XML_PAGE', 'Xml Page'), ('PLAINTEXT', 'Plaintext'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('OTHER', 'Other')], default='OTHER')),
                ('pageNumber', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.item')),
            ],
        ),
    ]
