# Generated by Django 5.1.4 on 2025-02-25 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0009_process_item_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('ERROR', 'Error'), ('AWAITING_HUMAN_INPUT', 'Awaiting Human Input'), ('AWAITING_HUMAN_VALIDATION', 'Awaiting Human Validation')], default='PENDING')),
                ('log', models.CharField(blank=True)),
                ('startDate', models.DateTimeField()),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual')], default='AUTOMATIC')),
                ('humanValidation', models.BooleanField(default=False)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.processingstepconfiguration')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.process')),
            ],
        ),
    ]
