# Generated by Django 5.1.4 on 2025-02-25 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('v2', '0010_processingstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationHandleValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlainHandleValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(blank=True)),
                ('resolveTo', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolveTo', models.URLField(blank=True)),
                ('view', models.CharField(blank=True)),
                ('language', models.CharField(blank=True)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('locationHandle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.locationhandlevalue')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v2.item')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v2.page')),
                ('projectMetadataTerm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.projectmetadataterm')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='v2_metadata_content_79be38_idx')],
            },
        ),
    ]
