# Generated by Django 5.1.4 on 2025-02-26 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0011_datevalue_locationhandlevalue_plainhandlevalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='lastModified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('ERROR', 'Error'), ('AWAITING_HUMAN_INPUT', 'Awaiting Human Input'), ('AWAITING_HUMAN_VALIDATION', 'Awaiting Human Validation')], default='PENDING'),
        ),
        migrations.AlterField(
            model_name='processingstep',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processingSteps', to='v2.process'),
        ),
        migrations.AlterField(
            model_name='processingstep',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('ERROR', 'Error'), ('AWAITING_HUMAN_INPUT', 'Awaiting Human Input'), ('AWAITING_HUMAN_VALIDATION', 'Awaiting Human Validation')], default='PENDING'),
        ),
    ]
