# Generated by Django 5.1.4 on 2025-02-26 14:22

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0012_process_lastmodified_process_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedValueType',
            fields=[
                ('basicvaluetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v2.basicvaluetype')),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=list, size=None)),
            ],
            bases=('v2.basicvaluetype',),
        ),
        migrations.AddField(
            model_name='projectmetadataterm',
            name='includeInExport',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='basicvaluetype',
            name='valueTypes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PLAINTEXT', 'Plaintext'), ('URL', 'Url'), ('DATE', 'Date'), ('PLAIN HANDLE', 'Plain Handle'), ('LOCATION HANDLE', 'Location Handle'), ('IIIF_HANDLE', 'Iiif Handle'), ('FIXED_VALUE', 'Fixed Value')]), default=list, size=None),
        ),
    ]
