# Generated by Django 5.1.4 on 2025-02-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0013_fixedvaluetype_projectmetadataterm_includeinexport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='fileType',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('PDF', 'Pdf'), ('XML', 'Xml'), ('PLAINTEXT', 'Plaintext'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('OTHER', 'Other')], default='OTHER'),
        ),
    ]
