# Generated by Django 5.1.4 on 2025-02-27 09:22

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0014_alter_page_filetype'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='metadataassignment',
            name='v2_metadata_content_79be38_idx',
        ),
        migrations.RemoveField(
            model_name='metadataassignment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='metadataassignment',
            name='object_id',
        ),
        migrations.AddField(
            model_name='datevalue',
            name='metadataAssignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v2.metadataassignment'),
        ),
        migrations.AddField(
            model_name='locationhandlevalue',
            name='metadataAssignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v2.metadataassignment'),
        ),
        migrations.AddField(
            model_name='locationhandlevalue',
            name='noid',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='metadataassignment',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='metadataassignment',
            name='textValues',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='plainhandlevalue',
            name='metadataAssignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v2.metadataassignment'),
        ),
        migrations.AddField(
            model_name='plainhandlevalue',
            name='noid',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='textvalue',
            name='metadataAssignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v2.metadataassignment'),
        ),
    ]
