# Generated by Django 5.1.4 on 2025-02-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0015_remove_metadataassignment_v2_metadata_content_79be38_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadataassignment',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='metadataassignment',
            name='textValues',
        ),
    ]
